name: Setup RDP and ngrok on Windows

on: [push]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Administrator User
      run: |
        $username = "adminuser"
        $password = ConvertTo-SecureString "C0mplexP@ssw0rd!" -AsPlainText -Force
        New-LocalUser -Name $username -Password $password -FullName "Admin User" -Description "Temporary Admin User"
        Add-LocalGroupMember -Group "Administrators" -Member $username
      shell: powershell

    - name: Create RDP user
      run: |
        $username = "jayras"
        $password = ConvertTo-SecureString "AnotherC0mplexP@ssw0rd!" -AsPlainText -Force
        New-LocalUser -Name $username -Password $password -FullName "RDP User" -Description "User for RDP access"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username
        Set-LocalUser -Name $username -PasswordNeverExpires $true
      shell: powershell

    - name: Enable RDP
      run: Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
      shell: powershell

    - name: Configure Firewall for RDP
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      shell: powershell

    - name: Download ngrok
      run: |
        Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive -Force -Path ngrok.zip -DestinationPath .
        Remove-Item ngrok.zip

    - name: Run installer as admin
      run: |
        $password = ConvertTo-SecureString "C0mplexP@ssw0rd!" -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential("adminuser", $password)
        Start-Process -FilePath ".\ngrok.exe" -Credential $credential -ArgumentList "install"
      shell: powershell

    - name: Set ngrok authtoken
      run: .\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      shell: powershell

    - name: Run ngrok for RDP
      run: .\ngrok.exe tcp 3389
      shell: powershell

    - name: Delete temporary admin user
      run: Remove-LocalUser -Name "adminuser"
      shell: powershell
